{
 "title": "OpenWebUI Stack",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "ollama_1, ollama_2, ollama_3, automatic1111, comfyui, open-webui, cadvisor, prometheus, grafana, pipelines"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"ollama_1\"}[$__rate_interval]))",
     "legendFormat": "ollama_1"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"ollama_2\"}[$__rate_interval]))",
     "legendFormat": "ollama_2"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"ollama_3\"}[$__rate_interval]))",
     "legendFormat": "ollama_3"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"open-webui\"}[$__rate_interval]))",
     "legendFormat": "open-webui"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"automatic1111\"}[$__rate_interval]))",
     "legendFormat": "automatic1111"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"ollama_1\"}[$__rate_interval]))+avg(rate(container_cpu_usage_seconds_total{name=\"ollama_2\"}[$__rate_interval]))+avg(rate(container_cpu_usage_seconds_total{name=\"ollama_3\"}[$__rate_interval]))",
     "legendFormat": "ollama_all"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{name=\"comfyui\"}[$__rate_interval]))",
     "legendFormat": "comfyUI"
    }
   ]
  },
  {
   "title": "Memory consumption (without cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"ollama_1\"}-container_memory_cache{name=\"ollama_1\"})",
     "legendFormat": "ollama_1"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=\"ollama_2\"}-container_memory_cache{name=\"ollama_2\"})",
     "legendFormat": "ollama_2"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=\"ollama_3\"}-container_memory_cache{name=\"ollama_3\"})",
     "legendFormat": "ollama_3"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=\"open-webui\"}-container_memory_cache{name=\"open-webui\"})",
     "legendFormat": "open-webui"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=\"automatic1111\"}-container_memory_cache{name=\"automatic1111\"})",
     "legendFormat": "automatic1111"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=\"comfyui\"}-container_memory_cache{name=\"comfyui\"})",
     "legendFormat": "comfyUI"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "System CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(avg without(mode) (1.0 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "CPU #{{cpu}}"
    }
   ]
  },
  {
   "title": "System RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes)",
     "legendFormat": "used system memory"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "available system memory" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "node_load5", "legendFormat": "load av 5s" },
    { "expr": "node_load1", "legendFormat": "load av 1s" },
    { "expr": "node_load15", "legendFormat": "load av 15s" }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU usage by $container ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "repeat": "container",
   "targets": [
    {
     "expr": "100.0 * (rate(container_cpu_usage_seconds_total{name=\"$container\"}[1m]))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Memory usage by $container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "repeat": "container",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=\"$container\"})",
     "legendFormat": "memory used"
    }
   ]
  }
 ]
}