services:
  pipelines:
    container_name: pipelines
    restart: always
    volumes:
      - ./pipelines:/app/pipelines
    image: ghcr.io/open-webui/pipelines:main
    networks:
      - llm-net
      - langfuse-net

  langfuse-db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - langfuse-net

  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      langfuse-db:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - HOSTNAME=0.0.0.0
      - NEXTAUTH_URL=http://0.0.0.0:3001
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    networks:
      - langfuse-net

volumes:
  database_data:
    driver: local

networks:
  langfuse-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.113.0.0/16
          gateway: 172.113.0.1 